# This is a basic workflow to help you get started with Actions

name: newReport

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 22 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  report:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        SEP_USER_NAME: ${{secrets.SEP_USER_NAME}}
        SEP_PASSWD: ${{secrets.SEP_PASSWD}}
        API_KEY: ${{secrets.API_KEY}}
        SMTP_PORT: ${{secrets.SMTP_PORT}}
        SMTP_SERVER: ${{secrets.SMTP_SERVER}}
        SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
        SENDER_EMAIL_PASSWD: ${{secrets.SENDER_EMAIL_PASSWD}}
        XINGMING: ${{secrets.XINGMING}}
        XUEYUAN: ${{secrets.XUEYUAN}}
        TELNUM: ${{secrets.TELNUM}}
        SAUID: ${{secrets.SAUID}}
        RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytz requests datetime
        python ./sub.py  
